package pessoa;

public enum Escolaridade {
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    POS_GRADUACAO_INCOMPLETO,
    POS_GRADUACAO_COMPLETO,
}
